apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.kafka }}
  labels:
    app: kafka
    app.kubernetes.io/component: message-broker
type: Opaque
stringData:
  # Post service Kafka client ID
  POST_KAFKA_CLIENT_ID: post-service
  
  # Kafka broker addresses
  KAFKA_BROKERS: {{ .Values.config.post.kafkaBrokers | default "kafka-cluster-kafka-bootstrap.kafka-operator.svc.cluster.local:9092" | quote }}
  
  # Kafka topics
  KAFKA_TOPIC: {{ .Values.config.post.kafkaTopic | default "microservice_one.events" | quote }}
  
  # Kafka consumer group
  KAFKA_GROUP_ID: {{ .Values.config.post.kafkaGroupId | default "post_service_outbox_publisher" | quote }}
  
  # Kafka configuration
  KAFKA_SECURITY_PROTOCOL: {{ .Values.config.post.kafkaSecurityProtocol | default "PLAINTEXT" | quote }}
  KAFKA_ENABLE_AUTO_COMMIT: {{ .Values.config.post.kafkaEnableAutoCommit | default "false" | quote }}
  KAFKA_AUTO_OFFSET_RESET: {{ .Values.config.post.kafkaAutoOffsetReset | default "earliest" | quote }}
  KAFKA_RETRIES: {{ .Values.config.post.kafkaRetries | default "5" | quote }}
  KAFKA_POLL_TIMEOUT: {{ .Values.config.post.kafkaPollTimeout | default "1.0" | quote }}