apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  labels:
    app: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.config.postgres.user | default "ishimwe" | quote }}
  POSTGRES_PASSWORD: "2025New+"
  POSTGRES_DB: {{ .Values.config.postgres.db | default "postgresgo1" | quote }}