apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.data.postgres.user | default "ishimwe" | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.data.postgres.password | default "2025New+" | quote }}
  POSTGRES_DB: {{ .Values.config.post.postgresDb | default "postgresgo1" | quote }}
  POSTGRES_HOST: {{ .Values.config.post.postgresHost | default "postgres.infrastructure.svc.cluster.local" | quote }}
  POSTGRES_PORT: {{ .Values.config.post.postgresPort | default "5432" | quote }}
  
  # Post service database
  DB_NAME: {{ .Values.config.post.postgresDb | default "postgresgo1" | quote }}
  DB_USER: {{ .Values.secrets.data.postgres.user | default "ishimwe" | quote }}
  DB_PASSWORD: {{ .Values.secrets.data.postgres.password | default "2025New+" | quote }}