apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis }}
  labels:
    app: redis
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  # Post service doesn't use Redis - this is a placeholder
  REDIS_PASSWORD: "placeholder"